name: Install helm
description: Installs Helm with specified version

inputs:
  version:
    description: "Version of Helm to install"
    default: "4.1.1"

runs:
  using: composite
  steps:
    - name: Install Helm
      shell: bash
      env:
        VERSION: v${{ inputs.version }}
      run: |
        curl -LO https://get.helm.sh/helm-${VERSION}-linux-amd64.tar.gz
        tar -zxvf helm-${VERSION}-linux-amd64.tar.gz
        sudo mv linux-amd64/helm /usr/local/bin/helm
